import { type ProgressRow } from "./progressColumns";

// TODO(API): 진행 관리 목록 API가 준비되면 이 파일을 삭제하고 useQuery로 교체한다.
// 바이어 이름·지역·계약 방식은 디자인 시안 값을 그대로 썼고,
// 날짜만 기한 경고(지연·임박·여유)가 모두 보이도록 조정했다.
export const PROGRESS_MOCK: ProgressRow[] = [
  {
    id: "pg-01",
    buyerName: "Antenna Retail",
    countryCode: "JP",
    city: "도쿄",
    contractType: "master_franchise",
    category: "korean_food",
    stage: "meeting",
    lastContactedAt: "2026-08-04",
    nextAction: "소개서 발송",
    nextActionDueAt: "2026-08-03", // 지연
  },
  {
    id: "pg-02",
    buyerName: "HK Dining Group",
    countryCode: "HK",
    city: "센트럴",
    contractType: "master_franchise",
    category: "beef_bbq",
    stage: "meeting",
    lastContactedAt: "2026-08-02",
    nextAction: "계약 조건 협의",
    nextActionDueAt: "2026-08-07", // 임박
  },
  {
    id: "pg-03",
    buyerName: "Marina Bay Concepts",
    countryCode: "SG",
    city: "마리나베이",
    contractType: "joint_venture",
    category: "korean_food",
    stage: "negotiating",
    lastContactedAt: "2026-08-05",
    nextAction: "계약서 검토",
    nextActionDueAt: "2026-08-19",
  },
  {
    id: "pg-04",
    buyerName: "Siam Table Partners",
    countryCode: "TH",
    city: "방콕",
    contractType: "distribution",
    category: "pork_bbq",
    stage: "legal_review",
    lastContactedAt: "2026-07-29",
    nextAction: "NDA 서명 요청",
    nextActionDueAt: "2026-08-08", // 임박
  },
  {
    id: "pg-05",
    buyerName: "Global Dining KR",
    countryCode: "JP",
    city: "오사카",
    contractType: "area_development",
    category: "korean_food",
    stage: "contacting",
    lastContactedAt: "2026-07-24",
    nextAction: "후속 메일 발송",
    nextActionDueAt: "2026-07-31", // 지연
  },
  {
    id: "pg-06",
    buyerName: "Prime F&B Group",
    countryCode: "HK",
    city: "침사추이",
    contractType: "licensing",
    category: "cafe",
    stage: "lead",
    lastContactedAt: null,
    nextAction: "첫 컨택",
    nextActionDueAt: null,
  },
  {
    id: "pg-07",
    buyerName: "Sakura Marketlink",
    countryCode: "JP",
    city: "요코하마",
    contractType: "master_franchise",
    category: "dessert",
    stage: "closed_won",
    lastContactedAt: "2026-05-30",
    nextAction: null,
    nextActionDueAt: null,
  },
  {
    id: "pg-08",
    buyerName: "Bangkok Prime Foods",
    countryCode: "TH",
    city: "파타야",
    contractType: "direct_operation",
    category: "korean_food",
    stage: "closed_lost",
    lastContactedAt: "2026-05-02",
    nextAction: null,
    nextActionDueAt: null,
  },
];
