/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 워크스페이스(브랜드) 목록
     * @description 활성 멤버십 브랜드를 가입 최신순으로 페이지네이션하여 반환합니다. data는 페이지 객체.
     */
    get: operations["list"];
    put?: never;
    /**
     * 워크스페이스(브랜드) 생성
     * @description brand + brand_member(owner) + subscription(tier1) + usage_counter 8건을 단일 트랜잭션으로 생성합니다. brand 계정만 호출 가능.
     */
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이메일 회원가입
     * @description 가입 성공 시 access/refresh 토큰과 사용자 정보를 반환합니다.
     */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * access token 재발급 (refresh 회전)
     * @description 유효한 refresh token으로 새 access/refresh를 발급하고 기존 refresh는 폐기합니다.
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정 요청 (메일 발송)
     * @description 가입 여부와 무관하게 항상 동일한 성공 응답을 반환합니다(가입 여부 노출 방지). 활성 이메일 계정에는 재설정 링크를, Google 가입 계정에는 안내 메일을 보냅니다.
     */
    post: operations["requestPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정 (토큰 검증)
     * @description 재설정 링크의 토큰과 새 비밀번호로 변경합니다. 성공 시 전 기기 로그아웃(모든 refresh 폐기). 자동 로그인 없음.
     */
    post: operations["confirmPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 현재 기기 로그아웃 (refresh 폐기) */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이메일 로그인
     * @description last_brand_id 폴백 포함. 성공 시 토큰과 사용자 정보를 반환합니다.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email-verify/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 인증 메일 재발송
     * @description 미인증 상태에서 인증 메일을 다시 보냅니다. 이미 인증된 경우 안내 메시지를 반환합니다.
     */
    post: operations["resendEmailVerification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email-verify/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이메일 인증 완료 (토큰 검증)
     * @description 인증 링크의 토큰으로 email_verified를 true로 만듭니다. 이미 인증된 경우 안내 메시지를 반환합니다.
     */
    post: operations["confirmEmailVerification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 헬스체크
     * @description DB 왕복 확인. 정상 200 CommonResponse<HealthData>, DB 실패 503 ErrorResponse(HEALTH_DATABASE_UNAVAILABLE).
     */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/brands/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 현재 워크스페이스 상세 (last_brand_id 기준)
     * @description 브랜드가 없거나 무효하면 data.brand = null로 200을 반환합니다.
     */
    get: operations["current"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 현재 로그인 사용자 조회 (세션 복구) */
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateBrandRequest: {
      /**
       * @description 워크스페이스 표시명 겸 브랜드 한국어명(1~255자)
       * @example 테스트 브랜드
       */
      nameKo: string;
    };
    /** @description 공통 오류 응답 { success:false, errorCode, message } */
    ErrorResponse: {
      /** @example false */
      success?: boolean;
      /** @example AUTH_INVALID_CREDENTIALS */
      errorCode?: string;
      /** @example 이메일 또는 비밀번호가 올바르지 않습니다. */
      message?: string;
    };
    BrandCreatedResponse: {
      brand?: components["schemas"]["BrandDetail"];
      subscription?: components["schemas"]["SubscriptionSummary"];
    };
    BrandDetail: {
      id?: string;
      nameKo?: string;
      nameEn?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseBrandCreatedResponse: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["BrandCreatedResponse"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    SubscriptionSummary: {
      /** @enum {string} */
      planCode?: "tier1" | "tier2" | "tier3";
      /** @enum {string} */
      status?: "active" | "trialing" | "past_due" | "cancelled";
      /** @enum {string} */
      billingCycle?: "monthly" | "annual";
    };
    SignupRequest: {
      /**
       * Format: email
       * @example test@example.com
       */
      email: string;
      /**
       * @description 영문 대소문자·숫자·특수문자 포함 8자 이상, 72바이트 이하
       * @example Aa1!aaaa
       */
      password: string;
      /** @example 지환 */
      name: string;
      /**
       * @description 가입 후 변경 불가
       * @example brand
       * @enum {string}
       */
      userType: "brand" | "buyer";
    };
    AuthResponse: {
      accessToken?: string;
      refreshToken?: string;
      /** Format: int64 */
      expiresIn?: number;
      user?: components["schemas"]["UserDto"];
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseAuthResponse: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["AuthResponse"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    UserDto: {
      id?: string;
      email?: string;
      name?: string;
      /** @enum {string} */
      userType?: "brand" | "buyer";
      emailVerified?: boolean;
      lastBrandId?: string;
    };
    RefreshRequest: {
      /** @description 로그인/가입 응답의 refreshToken */
      refreshToken: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseTokenResponse: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["TokenResponse"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    TokenResponse: {
      accessToken?: string;
      refreshToken?: string;
      /** Format: int64 */
      expiresIn?: number;
    };
    PasswordResetRequestRequest: {
      /**
       * Format: email
       * @example test@example.com
       */
      email: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseVoid: {
      /** @example true */
      success?: boolean;
      data?: Record<string, never>;
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    PasswordResetConfirmRequest: {
      /** @description 이메일 링크의 재설정 토큰 */
      token: string;
      /**
       * @description 영문 대소문자·숫자·특수문자 포함 8자 이상, 72바이트 이하
       * @example Aa1!aaaa
       */
      newPassword: string;
    };
    LogoutRequest: {
      /** @description 폐기할 현재 기기의 refresh token */
      refreshToken: string;
    };
    LoginRequest: {
      /**
       * Format: email
       * @example test@example.com
       */
      email: string;
      /** @example Aa1!aaaa */
      password: string;
    };
    EmailVerifyConfirmRequest: {
      /** @description 이메일 링크의 인증 토큰 */
      token: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseHealthData: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["HealthData"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    HealthData: {
      status?: string;
      db?: string;
      /** Format: int64 */
      latencyMs?: number;
      /** Format: date-time */
      timestamp?: string;
    };
    BrandSummary: {
      id?: string;
      nameKo?: string;
      nameEn?: string;
      /** @enum {string} */
      role?: "owner" | "user";
      /** Format: date-time */
      joinedAt?: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponsePageResponseBrandSummary: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["PageResponseBrandSummary"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    /** @description 목록 페이지 객체 { content, page, size, totalElements, totalPages, hasNext } */
    PageResponseBrandSummary: {
      content?: components["schemas"]["BrandSummary"][];
      /**
       * Format: int32
       * @description 0-based 페이지 번호
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @example 1
       */
      totalElements?: number;
      /**
       * Format: int32
       * @example 1
       */
      totalPages?: number;
      /** @example false */
      hasNext?: boolean;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseCurrentBrandResponse: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["CurrentBrandResponse"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    CurrentBrandResponse: {
      /** @description 워크스페이스가 없으면 null(항상 존재하는 필드) */
      brand: components["schemas"]["BrandDetail"];
      /**
       * @description 브랜드 있을 때만 포함
       * @enum {string}
       */
      role?: "owner" | "user";
      /** @description 브랜드 있을 때만 포함 */
      subscription?: components["schemas"]["SubscriptionDetail"];
    };
    SubscriptionDetail: {
      /** @enum {string} */
      planCode?: "tier1" | "tier2" | "tier3";
      /** @enum {string} */
      status?: "active" | "trialing" | "past_due" | "cancelled";
      /** @enum {string} */
      billingCycle?: "monthly" | "annual";
      /** Format: date-time */
      expiredAt?: string;
    };
    /** @description 성공 응답 공통 래퍼 { success:true, data, message } */
    CommonResponseMeResponse: {
      /** @example true */
      success?: boolean;
      data?: components["schemas"]["MeResponse"];
      /** @example 요청이 성공했습니다. */
      message?: string;
    };
    MeResponse: {
      user?: components["schemas"]["UserDto"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list: {
    parameters: {
      query?: {
        /** @description 0-based 페이지 번호 */
        page?: number;
        /** @description 페이지 크기(1~100) */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 소속 브랜드 페이지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponsePageResponseBrandSummary"];
        };
      };
      /** @description 인증 필요(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBrandRequest"];
      };
    };
    responses: {
      /** @description 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseBrandCreatedResponse"];
        };
      };
      /** @description nameKo 누락/초과(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증 필요(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description brand 계정 아님(BRAND_FORBIDDEN_USER_TYPE) / 워크스페이스 상한 초과(BRAND_WORKSPACE_LIMIT) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description plan 미시드(PLAN_NOT_SEEDED) 등 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description 가입 성공 — 토큰 발급 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseAuthResponse"];
        };
      };
      /** @description 필수값 누락 / 비밀번호 정책 위반 / userType 오류(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 이미 존재하는 이메일(AUTH_EMAIL_DUPLICATED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseTokenResponse"];
        };
      };
      /** @description refreshToken 누락(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 유효하지 않거나 만료/폐기된 refresh token(AUTH_REFRESH_TOKEN_EXPIRED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequestRequest"];
      };
    };
    responses: {
      /** @description 요청 접수(항상 동일 응답) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseVoid"];
        };
      };
      /** @description 이메일 형식 오류(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirmRequest"];
      };
    };
    responses: {
      /** @description 재설정 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseVoid"];
        };
      };
      /** @description VALIDATION_ERROR(토큰 누락/비밀번호 정책) / AUTH_RESET_TOKEN_INVALID / AUTH_RESET_TOKEN_EXPIRED / AUTH_RESET_TOKEN_USED */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description 로그아웃 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseVoid"];
        };
      };
      /** @description refreshToken 누락(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증 필요 / 토큰 무효(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseAuthResponse"];
        };
      };
      /** @description 필수값 누락(VALIDATION_ERROR) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 잘못된 자격증명(AUTH_INVALID_CREDENTIALS) / 삭제된 계정(AUTH_ACCOUNT_DELETED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  resendEmailVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 재발송 완료 또는 이미 인증됨 안내 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseVoid"];
        };
      };
      /** @description 인증 필요(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirmEmailVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailVerifyConfirmRequest"];
      };
    };
    responses: {
      /** @description 인증 완료 또는 이미 인증됨 안내 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseVoid"];
        };
      };
      /** @description VALIDATION_ERROR(토큰 누락) / AUTH_VERIFY_TOKEN_INVALID / AUTH_VERIFY_TOKEN_EXPIRED */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 정상 — CommonResponse<HealthData>{ status, db, latencyMs, timestamp } */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseHealthData"];
        };
      };
      /** @description DB 연결 실패(HEALTH_DATABASE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 현재 브랜드 상세 또는 data.brand = null */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseCurrentBrandResponse"];
        };
      };
      /** @description 인증 필요(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용자 정보 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseMeResponse"];
        };
      };
      /** @description 인증 필요(AUTH_UNAUTHORIZED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
